# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Charalampos Kardaris
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ckardaris.github.io" # the base hostname & protocol for your site, e.g. http://example.com
socials:
  - url: mailto:ckardaris@outlook.com
    svg: email
    alt: Email logo
    label: Send email to Charalampos Kardaris
  - url: /feed.xml
    svg: rss
    alt: RSS logo
    label: Open RSS feed of Charalampos Kardaris's blog
  - url: https://www.linkedin.com/in/ckardaris
    svg: linkedin
    alt: LinkedIn logo
    label: Visit LinkedIn profile
  - url: https://www.github.com/ckardaris
    svg: github
    alt: GitHub logo
    label: Visit GitHub profile
  - url: https://www.gitlab.com/ckardaris
    svg: gitlab
    alt: GitLab logo
    label: Visit GitLab profile
  - url: https://www.codeberg.org/ckardaris
    svg: codeberg
    alt: Codeberg logo
    label: Visit Codeberg profile
  - url: https://orcid.org/0009-0001-4670-4594
    svg: orcid
    alt: ORCID logo
    label: Visit ORCID profile

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-loading-lazy

header_pages:
  - blog.html
  - photography.html
  - about.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Makefile
  - Dockerfile

tag_page_layout: tag_page
tag_page_dir: blog/tags
